### PR TITLE
TODO and FIXME are now highlighted

### LINKED ISSUE #5: Color TODO and FIXME as was the case in Atom
Since we use these words a lot in kean, it would be nice to have them coloured so that they stand out.

### PR DESCRIPTION
**Pull request by thomasfanell**
Closes #5

### CODE REVIEW

**Comment by thomasfanell** [comment]
@simonmika @marcusnaslund Should we include `NOTE` here as well?

**Comment by marcusnaslund** [comment]
We just changed all `FIXME` to `TODO` to make them easier to find. :) But it doesn't hurt to have both. We don't really use `NOTE`, and I don't think we should. All comments are some sort of note.

**Comment by simonmika** [comment]
I agree. And I think that @marcusnaslund should add some kind of policy when to use `FIXME` and when to use `TODO`. Else we should have the policy of only using one of them.

**Comment by marcusnaslund** [comment]
Actually, I instated the policy of only using `TODO` earlier this week.

**Comment by thomasfanell** [comment]
Then maybe `FIXME` should be highlighted as invalid?

**Pull request merged**
